server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://eslzlaielhzfbn:590a06316a8ab14e89de586aea2db795ad98251f40d282b29bad001b3428ca67@ec2-35-170-85-206.compute-1.amazonaws.com:5432/d1oa93j9qi1oqt
    username: eslzlaielhzfbn
    password: 590a06316a8ab14e89de586aea2db795ad98251f40d282b29bad001b3428ca67
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto Bootcamp - Digital Innovation + Banco Santander - Version Backend.
  version: 2.0

